### ISSUE TITLE
[FEAT] - Integrate with Garmin 

### ISSUE THREAD

**Issue by Cave-Johnson** [joaovitoriasilva/endurain#3]
Would be great to add Garmin support - i know alot of people that would love to be able to self host something to pull in their Garmin data

https://github.com/cyberjunky/python-garminconnect

**Comment by dgalli1** [comment]
Wouldn't it be more useful to directly support .fit file imports instead of relaying on an API?

Like this smartwatches connected via gadgetbridge could also still work. 

Garmin also has a offical sdk, which should result in fewer stability issues:
https://developer.garmin.com/fit/overview/

The connect website also has a function to export fit files which would mean that it should still be possible to connect via the webpage for users in the offical eco system.

**Comment by joaovitoriasilva** [comment]
Hello @dgalli1. Yes, you are right. .fit files is on my to do list. Probably my next task. Every platform that I know supports .fit files, so it makes sense to support it.

Using an API has some other benefits like exporting other data than activities, i.e. all the health data that Garmin also has, like weight, HRV, etc

**Comment by alexanderadam** [comment]
> Wouldn't it be more useful to directly support .fit file imports instead of relaying on an API?

I think that both have different advantages and purposes.
Moving files manually can be inconvenient instead of having a sync that just works™.

However, I think that in order to use the API you'd need to be part of the [Garmin developer program](https://www.garmin.com/en-US/forms/GarminConnectDeveloperAccess/) and I'm not sure which conditions apply there.

> Like this smartwatches connected via gadgetbridge could also still work.

IMHO this _would_ be the best way since everything would stay within an open ecosystem. _However, [Gadgetbridge sync was requested 9 years](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/49) and I'm not sure that it'd be supported anytime soon.

> Using an API has some other benefits like exporting other data than activities, i.e. all the health data that Garmin also has, like weight, HRV, etc

That's true. But I can also imagine that it means a lot of work to implement these, or not?

**Comment by joaovitoriasilva** [comment]
Implemented in v0.6.0 version.
